const state = {
  running: false,
  words: [],
  spawnTimer: null,
  countdownTimer: null,
  animationFrameId: null,
  chaosThemeTimer: null,
  powerTimer: null,
  timeLeft: 60,
  duration: 60,
  score: 0,
  baseScore: 0,
  comboBonus: 0,
  popped: 0,
  attempts: 0,
  misses: 0,
  typedChars: 0,
  poppedChars: 0,
  powerUpsCollected: 0,
  streak: 0,
  bestStreak: 0,
  comboMultiplier: 1,
  nextId: 0,
  lastTick: 0,
  theme: "dark",
  level: 1,
  category: "general",
  wordDifficulty: "easy",
  accessibility: false,
  paused: false,
  rotationEnabled: false,
  activePower: null,
  powerEndsAt: 0,
  powerRemainingMs: 0,
  usedWords: new Set(),
  mobileDismissed: false,
};
