const state = {
  running: false,
  words: [],
  spawnTimer: null,
  countdownTimer: null,
  animationFrameId: null,
  chaosThemeTimer: null,
  timeLeft: 60,
  duration: 60,
  score: 0,
  popped: 0,
  streak: 0,
  bestStreak: 0,
  nextId: 0,
  lastTick: 0,
  theme: "dark",
  level: 1,
  rotationEnabled: false,
  usedWords: new Set(),
  mobileDismissed: false,
};
