const state = {
  running: false,
  words: [],
  spawnTimer: null,
  countdownTimer: null,
  animationFrameId: null,
  timeLeft: 60,
  score: 0,
  popped: 0,
  streak: 0,
  bestStreak: 0,
  nextId: 0,
  lastTick: 0,
  floaters: [],
  theme: "dark",
  themeCycleTimer: null,
  level: 1,
  rotationEnabled: false,
  mobileDismissed: false,
};
